### ISSUE TITLE
Add a new option to text user from their profile screen.

### ISSUE THREAD

**Issue by Shruti-1910** [Wave-2024/Wave#180]
**Description:**

Currently, the MoreOptionForOtherProfile widget provides options like Report, Block, Share To, Website Url, and Cancel. We need to add a "Message" option to this widget. Upon clicking this new option, the user should be directed to the message box to initiate a conversation.

**Steps to Reproduce:**

- Navigate to the profile of another user.
- Click on the More Options button.
- Observe the available options in the MoreOptionForOtherProfile widget.

**Expected Behavior:**

There should be a "Message" option in the MoreOptionForOtherProfile widget. Clicking on this option should redirect the user to the message box of the selected user.

**Actual Behavior:**

Currently, there is no "Message" option available in the MoreOptionForOtherProfile widget.

**Proposed Solution:**

- Add a new ListTile for the "Message" option in the MoreOptionForOtherProfile widget.
- Ensure that clicking on the "Message" option redirects the user to the message box for initiating a conversation.

**Comment by Alpha17-2** [comment]
Implemented in #200
