### ISSUE TITLE
Handling Multiple Spaces in Post Captions

### ISSUE THREAD

**Issue by Shruti-1910** [Wave-2024/Wave#182]
**Current Behavior:**

Currently, when a user adds a caption to a post, any leading or trailing spaces in the caption are displayed as-is. This can lead to captions that appear incorrectly formatted or visually unappealing.

**Expected Behavior:**

When a user adds a caption to a post, leading and trailing spaces should be trimmed. Spaces between words within the caption should remain unchanged to preserve intentional formatting choices such as line breaks or paragraphs.

**Acceptance Criteria:**

User Interface:

- Captions should appear clean and well-formatted, with leading and trailing spaces automatically removed.
- The UI should display the caption exactly as entered by the user in terms of spaces between words.

Functionality:

- The app should trim leading and trailing spaces from captions when they are saved or displayed.
- This functionality should apply both when the post is initially created and when it is edited.

**Comment by Alpha17-2** [comment]
I guess that's the expected behaviour. Blank spaces should only be trimmed from the leading and trailing , the spaces in between any two words in the caption should be decided by the user as it might be the way how the user wants to show the caption . @Shruti-1910

**Comment by Shruti-1910** [comment]
Thank you for your feedback. I apologize for any confusion caused. To clarify, the caption is currently not trimming the leading or the trailing spaces. Any spaces between words within the caption should be preserved exactly as entered by the user.
@Alpha17-2
