### ISSUE TITLE
Implement Message Deletion Options in Chat

### ISSUE THREAD

**Issue by Shruti-1910** [Wave-2024/Wave#191]
**Description:**

Currently, the app lacks the functionality to delete messages, both from the user's own view and from everyone's view in chat conversations. Message deletion options are essential for users to manage their communication history and maintain privacy. Implementing these options will enhance user control and privacy within the chat feature.

**Expected Behavior:**

- Users should have the option to delete messages they have sent from their own view.
- Users should also have the option to delete messages from everyone's view, including recipients' views.
- Deleted messages should be removed from the chat interface for all participants.

**Acceptance Criteria:**

1. User Interface:

- Implement UI elements (e.g., delete button or gesture) to initiate message deletion.
- Provide options for deleting messages from the user's view only or from everyone's view.

2. Functionality:

- Implement logic to delete messages securely and efficiently from both the frontend and backend.
- Ensure that deleted messages are immediately removed from the chat interface and not retrievable.

**Comment by Alpha17-2** [comment]
A duplicate issue of #170 and the feature is already implemented in #177 thereby closing it
