### ISSUE TITLE
Enable Direct Photo Management from Self Profile View

### ISSUE THREAD

**Issue by Shruti-1910** [Wave-2024/Wave#201]
**Description:**

Although there are existing options to change the profile picture and cover photo, users currently lack the ability to directly manage these photos by clicking on them within their own profile view. Implementing this feature will provide a more intuitive and direct method for users to manage their profile visuals, enhancing usability and user control within the app.

**Expected Behavior:**

- Allow users to click on their profile picture or cover photo within their own profile view to access options for changing, removing the photo or view the photo.
- Provide a streamlined interface that integrates existing photo management functionalities directly within the profile view.

**Acceptance Criteria:**

1. User Interface:

- Enhance the self-profile view to make profile picture and cover photo clickable for direct management actions.
- Design the interface to display intuitive options (e.g., change photo, remove photo, view photo) when users click on their profile visuals.

2. Functionality:

- Implement workflows that allow users to initiate changes to their profile picture or cover photo directly from their profile view.
- Ensure that clicking on the photo opens a menu or overlay with clear options for managing the photo.

**Comment by Alpha17-2** [comment]
Well , I have already implemented the `view image on tapping` in #202 and updating image logic would remain the same . Therefore closing the issue
