### ISSUE TITLE
Unexpected Behavior After User Registration

### ISSUE THREAD

**Issue by Shruti-1910** [Wave-2024/Wave#79]
After a user successfully registers for an account, they are presented with a snack bar message confirming account creation. However, the expected behavior is to immediately redirect the user to the home screen.

**Expected Behavior:**

- User completes the registration process.
- System successfully creates the account.
- User is automatically redirected to the Home Screen.

**Current Behavior:**

- User completes the registration process.
- System successfully creates the account.
- A snack bar message appears confirming account creation.
- User remains on the registration screen.

**Suggested Fix:**

- Implement logic to automatically redirect the user to the Home screen after successful registration.

**Comment by Alpha17-2** [comment]
Okay fix asap

**Comment by Shruti-1910** [comment]
Okay I am on it.
